config/routes.rb
ToDoList50::Application.routes.draw do
  devise_for :users
  devise_scope :user do
        get '/logout' => 'devise/sessions#destroy'
  end
  resources :tasks do

  

 

  collection do
    get 'completed'
    post 'complete'
    get 'incomplete'
    post 'incomplete'
    get 'search'
    post 'search'
    get 'today'
    post 'today'
end
  end
  get '/creators' => 'pages#creators'
  get '/help' => 'pages#help'
  root 'tasks#all'
end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :user
	
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :first_name, presence: true
  validates :last_name, presence: true
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :first_name
    devise_parameter_sanitizer.for(:sign_up) << :last_name
  end
end

app/controllers/pages_controller.rb
class PagesController <ApplicationController
def home
	@tasks=Task.all
end
def help
end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @task = current_user.tasks.build
    @tasks = current_user.tasks.order('created_at DESC')
  end
def all
    @tasks = Task.all()
  end
  # GET /tasks/1
  # GET /tasks/1.json



  def show
  end

  # GET /tasks/new
  def new
    @task = current_user.tasks.build
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = current_user.tasks.build(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render action: 'show', status: :created, location: @task }
      else
        format.html { render action: 'new' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end
  def search
    @tasks=Task.where(Task: params[:search])
  end
  def complete
      params[:task_checkbox].each do |check|
       task_id = check
       t = Task.find_by_id(task_id)
        t.update_attribute(:is_completed, true)
        t.save
     end
   
    redirect_to :action => 'index'
  end

  def completed
    @tasks=current_user.tasks.where(is_completed: true)
  end

  def incomplete
    @tasks= current_user.tasks.where(is_completed: false)
  end

   def today 
    @tasks = current_user.tasks.where(Deadline: Date.today)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:Task, :Category, :Deadline, :is_completed, :user_id)
    end
    def task_model      
      Task.owner(current_user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<%= javascript_include_tag 'rails' %>
 <%= javascript_include_tag :defaults %>
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/tasks">My To Do List</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      	<li><a href="/">Everyone's To Do List</a></li>
        <li><a href="/tasks/today">Today's Tasks</a></li>
        <li><a href="/help">Help</a></li>       
      	<li><a href="/creators">Creators</a></li>
        <% if user_signed_in? %>
            <li><font color="white"> You are currenty signed in as <%= current_user.email %></font> </li>
        <%= link_to "Sign out", logout_path, :method => :delete %>
        <% else %>
         <li> <font color="white"> <%= link_to "Sign up", new_user_registration_path %>
          or <%= link_to "Sign in", new_user_session_path %> </li>
        <% end %>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<html>
<head>
  <title>Chan-Yu To Do List</title>
  <%= stylesheet_link_tag    "flatly", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "flatly", "data-turbolinks-track" => true %>
 
  <%= csrf_meta_tags %>
</head>
<style>
body{height: 100%}
body {


   background-image: url('/assets/working.jpg');
   background-position: bottom;
   background-attachment: fixed;
   background-repeat: no-repeat;
   background-size: 100% 100%;
   color: #0A0670;
   

 }</style>

<%= yield %>

<footer id="footer"style="right">
    
                      <p>&copy; John Wesley Chan X Sean Tristan Yu 2014</p>
  </footer>
</body>
</html>

app/views/pages/creators.html.erb
<style>
body{height: 100%}
body {


   background-image: url('/assets/us.jpg');
   background-position: bottom;
   background-attachment: fixed;
   background-repeat: no-repeat;
   background-size: 100% 90%;
   color: #0A0670;
   

 }</style>

app/views/pages/help.html.erb
<h1>Help Page</h1>
<h2>Adding A New Task:</h2>
	<p>Simply Click on the "New Task" Link and it will direct you to a page. There, simply fill out the</p>
	<p> necessary fields to create a new task</p>
<h2>Editing An Existing Task:</h2>
	<p>Simply Click on the "Edit" Link beside the task that you wish to edit. It will direct you to a</p>
	<p>page to edit the selected task. There, simply edit the fields you wish to edit and then</p>
	<p>click the "Update Task" button.</p>
<h2>Marking a Task Done:</h2>
	<p>Basically, Press the Confirm Marked Task to permanently mark the task finished.</p>
<h2>Completed Task:</h2>
	<p> Press the Completed Task button. To view the tasks you have accomplished </p>
<h2> For more information and help: </h2>
<h4> Contact us : 09322627601 Sean Yu, 09277899999 Wesley Chan </h4>
<%= button_to 'Back to List', tasks_path, :class => 'btn btn-danger', :method => "get" %>

app/views/pages/home.html.erb
<h3>Sean and Wesley aims</h3>
<h3>to learn ruby and complete the cs21b course,</h3>
<h3>which is why we built</h3>
<h3>this To Do List,</h3>
<h3>not only to help us,</h3>
<h3>but to help everyone around us.</h3>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Task %><br>
    <%= f.text_field :Task %>
  </div>
  <div class="field">
    <%= f.label :Category %><br>
    <%= f.text_field :Category %>
  </div>
  <div class="field">
    <%= f.label :Deadline %><br>
    <%= f.date_select :Deadline %>
  </div>
  <div class="field">
    <%= f.label :is_completed %><br>
    <%= f.check_box :is_completed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/all.html.erb
<div class="col-sm-3 col-md-3 pull-right">
<%= form_tag("/tasks/search/", :method => "get") do %> 

  <div class="form-group">
    <%= text_field_tag :search %><%= submit_tag "Search", class: "btn btn-warning" %>
  </div>
  

  <% end %>
</div>
<h1>Everybodeh's tasks</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th>Task</th>
      <th>Category</th>
      <th>Deadline</th>
      <th>Is completed</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <%= form_tag("/tasks/complete/", :method => "post") do %>   
    <% @tasks.each do |task| %>
      <tr>
        <% if task.is_completed == true %>
     <td> <%= check_box_tag  "task_checkbox[]",task.id, task.is_completed %></td> <td> <strike><%= task.Task %></strike> </td>
  <% else %>
     <td> <%= check_box_tag  "task_checkbox[]",task.id, task.is_completed %></td> <td><%= task.Task %></td>
  <% end %>
        
        <td><%= task.Category %></td>
        <td><%= task.Deadline %></td>
        <td><%= task.is_completed %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        
      </tr>
    <% end %>
     <%= submit_tag("Confirm Marked Task(s)", :class=>"btn btn-success") %>
<%end%>
  </tbody>

</table>


<br>


<div style="float: left; width: auto ;"><%= button_to 'New Task', new_task_path, :class => "btn btn-primary", :method => "get" %></div>
<div style="float: left; width: auto ;"><%= button_to 'Completed Tasks', completed_tasks_path, :class => "btn btn-default", :method => "get" %></div>
<div style="float: left; width: auto ;"><%= button_to 'Incomplete Tasks', incomplete_tasks_path, :class => "btn btn-danger", :method => "get" %></div>

app/views/tasks/completed.html.erb
<h1>Completed Tasks</h1>

<table>
  <thead>
    <tr>
      
      <th>Task</th>
      <th>Category</th>
      <th>Deadline</th>
      
    </tr>
  </thead>

  <tbody>
  <%= form_tag("/tasks/completed/", :method => "post") do %>   
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.Task %></td>    
        
        <td><%= task.Category %></td>
        <td><%= task.Deadline %></td>
        
      </tr>
    <% end %>
<%end%>
  </tbody>

</table>

  <%= button_to 'Back to List', tasks_path, :class => 'btn btn-danger', :method => "get" %>


<br>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

 |
<%= button_to 'Back to List', tasks_path, :class => 'btn btn-danger', :method => "get" %>

app/views/tasks/incomplete.html.erb
<h1>Incompleted Tasks</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th>Task</th>
      <th>Category</th>
      <th>Deadline</th>
      <th>Is completed</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <%= form_tag("/tasks/complete/", :method => "post") do %>   
    <% @tasks.each do |task| %>
      <tr>
        <% if task.is_completed == true %>
     <td> <%= check_box_tag  "task_checkbox[]",task.id, task.is_completed %></td> <td> <strike><%= task.Task %></strike> </td>
  <% else %>
     <td> <%= check_box_tag  "task_checkbox[]",task.id, task.is_completed %></td> <td><%= task.Task %></td>
  <% end %>
        
        <td><%= task.Category %></td>
        <td><%= task.Deadline %></td>
        <td><%= task.is_completed %></td>
        
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        
      </tr>
    <% end %>
    <%= submit_tag("Confirm Marked Task(s)", :class=>"btn btn-success") %>

     
<%end%>

  </tbody>

</table>
<%= button_to 'Back to List', '/tasks', :class => 'btn btn-danger', :method => "get" %>

app/views/tasks/index.html.erb
<div class="col-sm-3 col-md-3 pull-right">
<%= form_tag("/tasks/search/", :method => "get") do %> 

  <div class="form-group">
    <%= text_field_tag :search %><%= submit_tag "Search", class: "btn btn-warning" %>
  </div>
  

  <% end %>
</div>
<h1>My Tasks</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th>Task</th>
      <th>Category</th>
      <th>Deadline</th>
      <th>Is completed</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <%= form_tag("/tasks/complete/", :method => "post") do %>   
    <% @tasks.each do |task| %>
      <tr>
        <% if task.is_completed == true %>
     <td> <%= check_box_tag  "task_checkbox[]",task.id, task.is_completed %></td> <td> <strike><%= task.Task %></strike> </td>
  <% else %>
     <td> <%= check_box_tag  "task_checkbox[]",task.id, task.is_completed %></td> <td><%= task.Task %></td>
  <% end %>
        
        <td><%= task.Category %></td>
        <td><%= task.Deadline %></td>
        <td><%= task.is_completed %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        
      </tr>
    <% end %>
     <%= submit_tag("Confirm Marked Task(s)", :class=>"btn btn-success") %>
<%end%>
  </tbody>

</table>


<br>


<div style="float: left; width: auto ;"><%= button_to 'New Task', new_task_path, :class => "btn btn-primary", :method => "get" %></div>
<div style="float: left; width: auto ;"><%= button_to 'Completed Tasks', completed_tasks_path, :class => "btn btn-default", :method => "get" %></div>
<div style="float: left; width: auto ;"><%= button_to 'Incomplete Tasks', incomplete_tasks_path, :class => "btn btn-danger", :method => "get" %></div>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= button_to 'Back to List', tasks_path, :class => 'btn btn-danger', :method => "get" %>

app/views/tasks/search.html.erb
<h1>Listing tasks</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th>Task</th>
      <th>Category</th>
      <th>Deadline</th>
      <th>Is completed</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <%= form_tag("/tasks/complete/", :method => "post") do %>   
    <% @tasks.each do |task| %>
      <tr>
        <% if task.is_completed == true %>
     <td> <%= check_box_tag  "task_checkbox[]",task.id, task.is_completed %></td> <td> <strike><%= task.Task %></strike> </td>
  <% else %>
     <td> <%= check_box_tag  "task_checkbox[]",task.id, task.is_completed %></td> <td><%= task.Task %></td>
  <% end %>
        
        <td><%= task.Category %></td>
        <td><%= task.Deadline %></td>
        <td><%= task.is_completed %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        
      </tr>
    <% end %>
     <%= submit_tag("Confirm Marked Task(s)", :class=>"btn btn-success") %>
<%end%>
  </tbody>

</table>


<br>


<div style="float: left; width: auto ;"><%= button_to 'New Task', new_task_path, :class => "btn btn-primary", :method => "get" %></div>
<div style="float: left; width: auto ;"><%= button_to 'Completed Tasks', completed_tasks_path, :class => "btn btn-default", :method => "get" %></div>
<div style="float: left; width: auto ;"><%= button_to 'Incomplete Tasks', incomplete_tasks_path, :class => "btn btn-danger", :method => "get" %></div>
<div style="float: left; width: auto ;"><%= button_to 'Back to List', tasks_path, :class => 'btn btn-danger', :method => "get" %></div>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Task:</strong>
  <%= @task.Task %>
</p>

<p>
  <strong>Category:</strong>
  <%= @task.Category %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @task.Deadline %>
</p>

<p>
  <strong>Is completed:</strong>
  <%= @task.is_completed %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= button_to 'Back to List', tasks_path, :class => 'btn btn-danger', :method => "get" %>

app/views/tasks/today.html.erb
<h1>Today's Tasks</h1>

<table>
  <thead>
    <tr>
      
      <th>Task</th>
      <th>Category</th>
      <th>Deadline</th>
      
    </tr>
  </thead>

  <tbody>
  <%= form_tag("/tasks/today/", :method => "post") do %>   
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.Task %></td>    
        
        <td><%= task.Category %></td>
        <td><%= task.Deadline %></td>
        
      </tr>
    <% end %>
<%end%>
  </tbody>

</table>

  <%= button_to 'Back to List', '/tasks', :class => 'btn btn-danger', :method => "get" %>


<br>